### ISSUE TITLE
Support multiple connect devices

### ISSUE THREAD

**Issue by mangelozzi** [raspberrypi/usbboot#112]
The raspberry pi imager can support mutliple windows, and flash multiple units at the same time.

However rpiboot does not seem to support multiple devices connected to the same computer.
I get an error that `sdb` is already in use when I try to run rpiboot again for the 2nd connected device.

Using Ubuntu 20.04.

**Comment by adampaul88** [comment]
When you run `rpiboot -l`, do you get the same issue?

**Comment by timg236** [comment]
Closed due to inactivity
