### ISSUE TITLE
Installer for Windows does not install the drivers but finishes installing rpi boot

### ISSUE THREAD

**Issue by randomhousegir** [raspberrypi/usbboot#118]
It says it successfully extracted the drivers but then it does not install them. I am running as administrator but when I try to use rpi boot it does not connect or allow USB access.
![rpiboot_setup(1)_Pjcv4Lo2P1](https://user-images.githubusercontent.com/100244803/155236517-1483e441-266d-473c-af2f-d682d6fa5882.png)
![rpiboot_setup(1)_ZTvS2IQ3Kp](https://user-images.githubusercontent.com/100244803/155236522-59442cc2-e6c1-43b8-a7fe-c6b43a76269e.png)
![rpiboot_setup(1)_GUbGU3CO76](https://user-images.githubusercontent.com/100244803/155236526-7dc4715f-9d89-4bc7-9205-0ddc252b62e4.png)
 I am unsure how to get the drivers to install so I can set up an image on the emmc

**Comment by timg236** [comment]
You probably need to wait a long time for the installer to close and then reboot. Although, since the Windows version is not actively supported it's better run this on X86 Linux or a Raspberry Pi.

**Comment by timg236** [comment]
I retested on my Windows PC after uninstalling the driver and it does complete. It takes long time for the driver registration to complete so be careful to not close the command window which appears.
