### ISSUE TITLE
CM4 hangs

### ISSUE THREAD

**Issue by mikev1963** [raspberrypi/usbboot#135]
I am trying to load a new os, but when I run the following command it Hangs,  Ran for 1 day and I only see the following:

sudo ./rpiboot
RPIBOOT: build-date May  1, 2022 version 20220427-095022 54a0395d
Waiting for BMC2835/6/7/2711...
Loaded embedded: bincode4.bin
Sending bootcode.bin
Successfully read 4 bytes
Waiting for BCM2835/6/7/2711....     **<- hangs here for over 1 day,**

in /var/log/syslog:

usb disconnect errors

**Comment by Vishwasrao1** [comment]
I am also facing same issue on MacOs 

- I also tried to downgrade libusb version to previous one that I was using with old usbboot., however it won't work.  

- I tried changing usb cables so it won't work.

- Also I  tried to restore previous version of usbboot however it shows, rpiboot command not found.

**Comment by mikev1963** [comment]
This did not work for me😂

**Comment by mikev1963** [comment]
I got it to work.  Here is what I did.

1. powered off RPI CM4.
2. Ran the steps above from Vishwarao1
3. Powered on device.

Worked like a champ.  Crazy.
