### ISSUE TITLE
[Question] Where is the source located of `msd/bootcode.bin` & `msd/start*.elf`?

### ISSUE THREAD

**Issue by WeeJeWel** [raspberrypi/usbboot#144]
I'd like to view an example on how to compile my own bootable firmware (specifically to try flashing a CM4 over WebUSB for fun).

Is this source available anywhere?

**Comment by pelwell** [comment]
The VPU firmware is closed-source. The recommended method for a task such as the one you describe is to create a Buildroot Linux system with an initrd that does the job.

**Comment by timg236** [comment]
Take a look at the msd gadget for an example kernel and initrd. The ARM stage loading does not require Linux so you can replace the kernel with bare metal
ARM code

**Comment by cleverca22** [comment]
> specifically to try flashing a CM4 over WebUSB for fun

already implemented that!
https://github.com/librerpi/rpi-tools/tree/master/webusbboot

**Comment by WeeJeWel** [comment]
> > specifically to try flashing a CM4 over WebUSB for fun
> 
> already implemented that! https://github.com/librerpi/rpi-tools/tree/master/webusbboot

Yes, that’s nice, but it mounts as MSD which then isn’t available anymore from a browser.
