### ISSUE TITLE
rpiboot stops at File read: start4.elf

### ISSUE THREAD

**Issue by camopov** [raspberrypi/usbboot#166]
rpiboot stops at File read: start4.elf 
![Unbenannt](https://user-images.githubusercontent.com/96944108/202288418-59e64fc5-ebca-41a2-b8c6-1b05c2657545.PNG)

**Comment by pelwell** [comment]
1. What device are you trying to boot/enable MSD gadget on?
2. How up to date is the usbboot repo you built from? What's the top commit?

**Comment by pelwell** [comment]
3. Is there a flashing LED pattern on the device? If so, how many long and short flashes?

**Comment by camopov** [comment]
Thanks I was using an older version
