### ISSUE TITLE
wlan0 goes missing after working for a while

### ISSUE THREAD

**Issue by ksumit12** [raspberrypi/usbboot#167]
recently i tried to secure boot cm4 and it was not working due to some bug in latest version of pieeprom which @timg236 fixed it  by reverting back to older version . after that it worked perfectly and  wifi seems to work perfectly but in one cm4 it stopped in middle of an update and when did ifconfig wlan0 was missing and after that wlan0 /wifi didn't worked until i flashed that cm4 again using the rpi- imager and just copy pasting the boot.img and boot.sig that worked for me earlier.
only difference here i did change cmdline a little
`console=tty1 root=PARTUUID=21e60f8c-02 rootfstype=ext4 fsck.repair=yes rootwait  init=/usr/lib/raspberrypi-sys-mods/firstboot systemd.run=/boot/firstrun.sh systemd.run_success_action=reboot systemd.unit=kernel-command-line.target`
to
`console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 fsck.repair=yes rootwait  systemd.run=/boot/firstrun.sh systemd.run_success_action=reboot plymouth.ignore-serial-consoles `
nothing else was changed from the standard process of secure boot

i don't understand what could have been gone wrong here and how wifi works for some time and then suddenly stops working , having this issue with two secure booted cm4 not just one.
also i had `init=/usr/lib/raspberrypi-sys-mods/firstboot`  in cmdline.txt which kept the cm4 rebooting endlessly

**Comment by timg236** [comment]
There’s no connection between usbboot the EEPROM and WIFi.
I think OS support issues are best asked on the forum
