### ISSUE TITLE
WSL build info missing dependencies

### ISSUE THREAD

**Issue by kfilipan** [raspberrypi/usbboot#174]
### Describe the bug

Not sure if this is relevant but with latest distros in WSL, you also need to install `gcc` and `make` packages (and their automatic dependencies) otherwise the compiling fails - see complete steps below.

### Ubuntu/Debian

> Info for WSL installation: https://www.linuxfordevices.com/tutorials/linux/install-debian-on-windows-wsl

Install Ubuntu/Debian on WSL and start:

``` Shell
wsl -d <distro> # use Ubuntu or Debian
```

Change to user directory and update packages:

``` Shell
cd
sudo apt update
sudo apt upgrade
```

Install required modules (`gcc` and `make` are needed):

``` Shell
sudo apt install git libusb-1.0-0-dev pkg-config gcc make
```

Clone repository and compile:

``` Shell
git clone --depth=1 https://github.com/raspberrypi/usbboot
cd usbboot
make
```

Start USB boot script:

``` Shell
sudo ./rpiboot
```

### Device(s)

Other

**Comment by timg236** [comment]
I don't think we need specific instructions for WSL, I'm sure people can figure out how to install gcc / make on platforms they aren't already present.
