### ISSUE TITLE
[Request] Support booting from SD1

### ISSUE THREAD

**Issue by alberto2033** [raspberrypi/usbboot#19]
As discussed in the [forum](https://www.raspberrypi.org/forums/viewtopic.php?f=98&t=181744) it would be nice to be able to boot from an external SD card connected to GPIO34-39.

An improvement on this would be to be able to set the width of the data bus so 8 bit is also supported, using pins GPIO34-43

**Comment by lurch** [comment]
I think https://github.com/raspberrypi/firmware/issues would be the correct place for this issue, rather than here?
