### ISSUE TITLE
Contradicting documentation: rpiboot GPIO pins

### ISSUE THREAD

**Issue by mozzbozz** [raspberrypi/usbboot#190]
### Describe the bug

This is the documentation of the `program_rpiboot_gpio` option:
https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/raspberry-pi/bcm2711-bootloader.adoc#program_rpiboot_gpio

It says:
> Only one GPIO may be selected and the available options are 2, 4, 5, 7, 8

In this document, though: https://github.com/raspberrypi/usbboot/blob/master/secure-boot-recovery/README.md

...it says:

> The available GPIOs are 2,4,5,6,7,8 since these are high by default.

So: Is GPIO 6 available to be used for this option or not? In one of the two places, the documented information is wrong and should be fixed.

### Steps to reproduce the behaviour

n/a

### Device(s)

Other

**Comment by nathan-contino** [comment]
We can close this one. Yes, 6 is available for this option.
