### ISSUE TITLE
Following install of Home Assistant, USBboot stops working

### ISSUE THREAD

**Issue by tyon2006** [raspberrypi/usbboot#204]
### Describe the bug

This is my carrier board: https://www.makerfabs.com/raspberry-pi-cm4-tv-stick.html
This is the OS that seems to have broken it: https://www.home-assistant.io/
_I've submitted a request for help with each team for help as well, just trying to rule out the source of the problem._ 

I've installed many OSs via my carrier board and I've never had a problem before, but after installing Home Assistant, my CM4 with mmc has stopped appearing with USBBoot. I'm following the same steps I always have, but suddenly it no longer appears as a USB device. There is no response on the cmd while plugging the device in. My carrier board does not allow the use of an SD card with an MMC CM4, so it's effectively bricked. 

### Steps to reproduce the behaviour

The process I use is:

1. Launch RPIBoot on the Windows PC
2. Press and hold the button on the carrier board
3. Plug in the USB cable
4. Release the button
5. Then, nothing happens, where before, it would appear as a USB storage device

Carrier board instructions (at the bottom): https://github.com/magic-blue-smoke/Raspberry-Pi-CM4-TV-Stick

### Device(s)

Raspberry Pi CM4

### Compute Module IO board.

https://github.com/magic-blue-smoke/Raspberry-Pi-CM4-TV-Stick

### RPIBOOT logs

none

### Kernel logs

none

### Device UART logs

cannot access device to tell

**Comment by nbuchwitz** [comment]
Please post the output of rpiboot (verbose). Which version of rpiboot are you using?

**Comment by timg236** [comment]
rpiboot runs before firmware loads the EMMC so the OS cannot impact rpiboot behavior.

Most likely this is an intermittent with the host or carrier board - see troubleshooting guide
https://github.com/raspberrypi/usbboot?tab=readme-ov-file#troubleshooting

In addition to the rpiboot verbose output UART logs are normally required.

**Comment by timg236** [comment]
Closed due to inactivity
