### ISSUE TITLE
rpiboot always installs to /usr/..., should allow setting the prefix

### ISSUE THREAD

**Issue by bringert** [raspberrypi/usbboot#208]
### Describe the bug

Most software allows the user installation to select an installation prefix when building from source. Commonly this is /usr/local. rpiboot/Makefile has hardcoded installation into /usr.

### Steps to reproduce the behaviour

* Follow the build instructions at https://github.com/raspberrypi/usbboot/blob/master/Readme.md#building
* Install with `make install`

Observed:
The code is installed under /usr.

Expected: 
Some way to direct it to install under /usr/local without having to edit the Makefile

### Device(s)

Other

**Comment by tdewey-rpi** [comment]
Closing as fixed. Commit was merged back in April.
