### ISSUE TITLE
Disconnect device

### ISSUE THREAD

**Issue by neil-benn** [raspberrypi/usbboot#224]
**Is your feature request related to a problem? Please describe.**
I am setting up a system to reset CM4 devices to factory settings - however I need to reset the partitions and then replace the eeprom which requires me to power cycle the target CM4 between partition clearing and resetting the eeprom.  Is there a way to disconnect a device once rpiboot has connected it?

**Describe the solution you'd like**
An rpiboot command witha command line switch to disconnect teh edvice and if not then some bash command(s) to disconnect teh device.

**Describe alternatives you've considered**
Using a hardware solution with a switch on a relay connected to a GPIO port but that is a lot of work for the solution.

**Comment by timg236** [comment]
Set `recovery_reboot=1` in the config.txt file in the `recovery` sub-directory. 

Make sure that you have the latest version of the code / recovery.bin.

**Comment by neil-benn** [comment]
Thanks, can I ask what that does; sorry to be dense!
