### ISSUE TITLE
Reboot via signal from computer (UX Quality Of Life)

### ISSUE THREAD

**Issue by mofosyne** [raspberrypi/usbboot#241]
**Is your feature request related to a problem? Please describe.**
Problem is after flashing, I have to manually reboot.  This is fine, but hoping to automate this.

**Describe the solution you'd like**
Would be nice to be able to auto trigger a reboot (And also if possible optionally disable eMMC boot on reboot)

Perhaps you could either expose a serial interface or maybe a HID device or perhaps upon detection of a special file read, to which you can request a reboot.

**Describe alternatives you've considered**
Manually rebooting by hand. Works but is annoying.

**Additional context**
Currently autodetecting the CM4 via an approach like below, so a bash friendly (and as driverless approach) would be appreciated.

```bash
# Locate RPI CM4 Via USB
DEVICE=$(lsscsi -N | grep "RPi-MSD-" | awk '{print $NF}')
if [ -z "$DEVICE" ]; then
    # Not yet booted
    rpiboot
    sleep 3s
    DEVICE=$(lsscsi -N | grep "RPi-MSD-" | awk '{print $NF}')
    if [ -z "$DEVICE" ]; then
        echo "Raspberry Pi storage device not found."
        exit 1
    fi
fi

# Making sure to unmount all partition (FYI: '?' is a glob pattern so that `sdX?*` matches /dev/sdX1 /dev/sdX2, etc...)
sudo umount $DEVICE?* || /bin/true
```

**Comment by tdewey-rpi** [comment]
Closing as 'Won't address'. While this is a valuable idea, `rpiboot` is the wrong mechanism for it - `rpiboot` hands off to a booted payload, and that payload should handle your requirements.

As @timg236 points out, `rpi-sb-provisioner` will actually do this for you, and as it's open source and permissively licensed you're free to customise your install to your needs - or even borrow components from it. For your reboot case, `rpi-sb-provisioner` doesn't automatically reboot, as this wouldn't produce the desired behaviour in that flow (where you keep the IO board configured for `rpiboot`). Running the gadget yourself, you should be able to just issue `fastboot reboot`, however - making sure you've configured your IO board appropriately.

Finally, @timg236 has pointed out a mechanism to do this via the `mass-storage-gadget64` example, which could also work (albeit with more interventions required if mass-provisioning!).
