### ISSUE TITLE
usbboot/libusb cannot parse endpoints on windows 7

### ISSUE THREAD

**Issue by saltpotato** [raspberrypi/usbboot#28]
Hy,

I cannot really explain the cause.

On some machines with windows 7 rpiboot fails.
Windows 10 works in my particular instance.

Here the output from "rpiboot -v"
```
Found device 4 idVendor=0x04f2 idProduct=0xb51c
Bus: 1, Device: 5 Path: 1-9
Found device 5 idVendor=0x0a5c idProduct=0x2764
Bus: 1, Device: 19 Path: 1-1.3
Device located successfully
libusb: error [parse_endpoint] invalid extra ep desc len (0)
libusb: error [raw_desc_to_config] parse_configuration failed with error -1
libusb: warning [winusbx_claim_interface] auto-claimed interface 0 (required to
claim 1 with WinUSB)
Failed to claim interface
```
In the above log-messages, the messages prefixed by "libusb:"
are showing that the endpoint cannot be parsed and thus cannot send bootcode.bin.

Ignoring the error (compile by vs-2012) does not help.

I could be a driver issue, but it could also be solved by the app.
I dont know, a direction would be appreciated.

(I am not a driver expert and looking into libusb is a bit ... on most machines i obeserved, it does work)

i have also a usb-tree good-bad diff...

From the usb-treeview on both machines, left side results in good cmboot, right side bad -.

![good_bad](https://user-images.githubusercontent.com/7920968/34733194-cef735b8-f567-11e7-88ff-e3020616fb45.png)

Observations from the diff:
-configuration desriptor has more data bigger ( bad has 0x55, good 0x32 )
-bad reports eventually a empty interface as third interface 
-good has appearantly a out/out interface, bad has out/in, bad might be the winner here
-endpoint adresses are not the same (at least meant for the out endpoint), even...

Maybe this might be interesting because some machines dont work.
-and they all got usb3 only ( intel usb 3.0 extensible Hostcontroller )

I know this is very specific and is not really an issue of rpiboot itself.

 Thanks Martin

-update 
It might also be a libusb issue, since i wrote myself an example only using winusb (https://github.com/madwizard-thomas/winusbnet)

and this one works always finding the endpoints
(see txt, its a c# program, converted from usbboot/main.c)

  
[rpiboot.txt](https://github.com/raspberrypi/usbboot/files/1646271/rpiboot.txt)

**Comment by ghollingworth** [comment]
What x86 hardware is this?  I think this is possibly a problem with the Windows PC hardware complaining about a response being too long.  This is a known issue and thought only to effect Macs, but it's possible it's not limited to the Mac

**Comment by MartinSchulze1** [comment]
runnig dx-diag and display-related sections removed...
[DxDiag.txt](https://github.com/raspberrypi/usbboot/files/1616120/DxDiag.txt)

**Comment by ghollingworth** [comment]
Not sure what it is that is wrong in this, I'd really need to run the USB analyser in the failing case to understand what is different...

Is this only on a specific Windows 7 computer?  Does it happen with all compute modules or just this one in particular...

Gordon

**Comment by ghollingworth** [comment]
Closing assuming it is the same problem as seen on a small number of Mac machines (assuming they share the same USB root hub hardware.
