### ISSUE TITLE
rpiboot is busy-waiting ?!?

### ISSUE THREAD

**Issue by laf0rge** [raspberrypi/usbboot#45]
On a fairly high-end i7-6500U based system, rpiboot is consuming 7 to 11 percent of CPU without doing something. What a nightmare.  If you're waiting for a USB device to enumerate, you can actually register for events.  I  don't get why there should ever be any polling or busy-waiting/looping involved.

http://libusb.sourceforge.net/api-1.0/group__libusb__hotplug.html describes how to register a call-back for hot-plug event notification.

**Comment by ghollingworth** [comment]
Unfortunately this interface is not available for all applicable operating systems and therefore wasn't implemented...  

 LIBUSB_CAP_HAS_HOTPLUG to confirm that hotplug support is available.
