### ISSUE TITLE
Circular loop between raspberrypi/usbboot title or description and raspberrypi/tools/usbboot readme.md

### ISSUE THREAD

**Issue by stevenhoving** [raspberrypi/usbboot#52]
This git repo title/description says:
> Raspberry Pi USB booting code, moved from tools repository

The raspberrypi tools repository readme.md
https://github.com/raspberrypi/tools/blob/master/usbboot/Readme.md
Says:
> Please note, this code has now moved to
https://github.com/raspberrypi/usbboot.git

While I love these circular loops jokes, I can imagine that this was not done on purpose. Maybe fix this project title/description?

**Comment by pelwell** [comment]
Huh? The tools repo says it has been moved to usbboot, while the usbboot repo says it has been moved from the tools repo.

**Comment by stevenhoving** [comment]
> Huh? The tools repo says it has been moved to usbboot, while the usbboot repo says it has been moved from the tools repo.

yup

**Comment by pelwell** [comment]
And that's a problem?

**Comment by robindegen** [comment]
@pelwell Which one is correct? One of them has to be updated right?

**Comment by stevenhoving** [comment]
not really, but just say that it can be confusing. I got a good laugh out of it when I noticed it.

**Comment by stevenhoving** [comment]
> And that's a problem?

not really, but just say that it can be confusing. I got a good laugh out of it when I noticed it

**Comment by pelwell** [comment]
It's not so much a circularity, more of a doubly-linked list. You could argue that the "from" comment is unnecessary, but it's a way of saying "this is the new home of the usbboot utility that you may have seen elsewhere."

**Comment by stevenhoving** [comment]
Ah, now i see. I read over the 'from'' part. Sorry to cause confusion, especially on a Sunday.
