### ISSUE TITLE
can this lead to the pi turning off?

### ISSUE THREAD

**Issue by Lewiscowles1986** [raspberrypi/usbboot#54]
I'm working with this code, or some variant via the ClusterHAT and I'm seeing behavior across several pi-zero's 1.2 &1.3 (no wifi or headers). The pi's respond to ping over gadget mode, but not ssh or other commands. Sometimes they wake after a time. Other-times not. A Power cycle works

**Comment by lurch** [comment]
Sounds like a problem with whatever "gadget mode" code you're actually running on the Pi Zeros? In which case this is probably a question for the Raspberry Pi Forums. This repo is "just" the tool to load code onto the Pis :wink:

**Comment by Lewiscowles1986** [comment]
I was asking due to the clusterHAT turning off / stalling devices. But thanks
