### ISSUE TITLE
Install target missing in Makefile. Program loops forever

### ISSUE THREAD

**Issue by tvoverbeek** [raspberrypi/usbboot#7]
Makefile is missing install target.
Intentional?
If so Readme has to be updated to use ```sudo ./rpiboot```.
Since loop variable is initialized as 1 the program will loop forever and the ```-l``` option is meaningless.

**Comment by ghollingworth** [comment]
Yes, I've removed the install target for the moment, not sure it's the right solution for this...

Must have changed the loop=1 which debugging and forgot!
