### ISSUE TITLE
Selecting USB port message loop

### ISSUE THREAD

**Issue by JE-Tv1** [raspberrypi/usbboot#72]
When I use the option to look for CMs attached to USB port, the Rpiboot continues to output "Loading embedded: bootcode.bin".
I am currently using a raspberry pi 4 B to boot a CM3+ with CMIO. 

Is there any way to not get these infinite messages and just like the usual blank waiting?

![RpiBootStuck](https://user-images.githubusercontent.com/77734241/107532524-475a7180-6bbe-11eb-830a-e26c2b086d43.png)

**Comment by stephenglynch** [comment]
Also have this issue on windows 10 with a CM4 via USB

**Comment by vanarebane** [comment]
Same issue here.

I have a 1G RAM, 8G eMMC without wifi module that works fine on the official IO board.

Then I have a 4G RAM, 8G eMMC with wifi that has the same loading loop as others here.

So only difference is the board, drivers and IO board is working

**Comment by salmanfarisvp** [comment]
@vanarebane can you share how you solved the issue?

**Comment by vanarebane** [comment]
@salmanfarisvp that's right, just used another port. Maybe windows assigns some drivers to specific port? I have seen some other device drivers also fixed by switching ports

**Comment by salmanfarisvp** [comment]
@vanarebane Thanks 👍. I was using balena Fin v1.

**Comment by CrowntailTW0608** [comment]
I've the same issue
and I removed all USB devices (including mouse) to solved the problem

**Comment by lenkapolaskova** [comment]
Hello,
I have the same problem. Selecting another port does not solve the problem.

**Comment by cvabc** [comment]
Sample problem here on a windows 11 pc for cm4.

**Comment by timg236** [comment]
No response from OP. Closing.

N.B. We can't provide support for the multitude of Windows versions and USB versions. I recommend using a Raspberry Pi or Linux PC as the host and avoiding hubs.

**Comment by nerososft** [comment]
> Sample problem here on a windows 11 pc for cm4.

me too

**Comment by carlonluca** [comment]
For those with the same problem in a VMWare machine, I solved by setting the USB to version 2 instead of 3 in the machine settings.

**Comment by bigttys0** [comment]
Data packets sent to and from the USB port must be exactly 8 bytes in size. Any packets sent with a size that is not 8 bytes will not be read correctly by the USB port and may cause errors or data loss. To ensure reliable communication between the USB port and the device, it is important to ensure the exact size of data packet is sent.

Or, use USB2.

**Comment by wangchaoHZ** [comment]
i have the same issue too，CM4 on Windows 10
