### ISSUE TITLE
Create a tag or release?

### ISSUE THREAD

**Issue by markand** [raspberrypi/usbboot#84]
Hi there,

I'm a [Alpine Linux](http://alpinelinux.org) packager, I'd like to package usbboot into our repositories but our policy is usually to stick to a specific version rather than fixing an arbitrary git commit.

Since the activity is pretty low as the software is quite stable enough, is there any chance that you create at least a tag so that we can stick to it?

**Comment by timg236** [comment]
I've created a tag for the current version

https://github.com/raspberrypi/usbboot/releases/tag/v2021.07.01

**Comment by markand** [comment]
Thanks!
