### ISSUE TITLE
Raspberry Pi USB boot Setup fail on Win7 system

### ISSUE THREAD

**Issue by evan0csp** [raspberrypi/usbboot#91]
I'm run the rpiboot_setup.exe on win7 with CM4/IO board.
The setup was completed successfully.
But I find there has below information:
...
Installing BCM2710 driver...
Execute:"..."
Driver install returned -9
Installing BCM2711 driver...
Execute:"..."
Driver install returned -9
...
And I found that in Computer Device manager,
There has BCM2711 boost and shows the device are not installed.(Code28)

**Comment by timg236** [comment]
There is no support for Windows 7. 

Raspberry Pi OS is the only officially supported platform, although, we accept patches for other Operating Systems.
